
CREATE DATABASE opis;
CREATE USER opisuser WITH PASSWORD 'Op1SuS3r*227*12'; 
\CONNECT opis;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO opisuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO opisuser;